// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeVmcQw-TREPJ-CBP9TBetRkzesPUsupY',
    appId: '1:513756977022:web:fb1a3f127776e15826c52f',
    messagingSenderId: '513756977022',
    projectId: 'go2car-2150e',
    authDomain: 'go2car-2150e.firebaseapp.com',
    storageBucket: 'go2car-2150e.firebasestorage.app',
    measurementId: 'G-EH2S1DNV0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGy9HjAJyUrn4DJ6mhzKjfZCpAdB6V4bo',
    appId: '1:513756977022:android:54b4b7dfbf79bb9d26c52f',
    messagingSenderId: '513756977022',
    projectId: 'go2car-2150e',
    storageBucket: 'go2car-2150e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrTNE_jSBSJN8_bPJaUkZzzh5SNBB4G6I',
    appId: '1:513756977022:ios:8b8626b9ec903f6926c52f',
    messagingSenderId: '513756977022',
    projectId: 'go2car-2150e',
    storageBucket: 'go2car-2150e.firebasestorage.app',
    iosBundleId: 'com.example.go2car',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrTNE_jSBSJN8_bPJaUkZzzh5SNBB4G6I',
    appId: '1:513756977022:ios:8b8626b9ec903f6926c52f',
    messagingSenderId: '513756977022',
    projectId: 'go2car-2150e',
    storageBucket: 'go2car-2150e.firebasestorage.app',
    iosBundleId: 'com.example.go2car',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeVmcQw-TREPJ-CBP9TBetRkzesPUsupY',
    appId: '1:513756977022:web:47d20c75ce4b942526c52f',
    messagingSenderId: '513756977022',
    projectId: 'go2car-2150e',
    authDomain: 'go2car-2150e.firebaseapp.com',
    storageBucket: 'go2car-2150e.firebasestorage.app',
    measurementId: 'G-EQGFLM7ZG5',
  );
}
